### PR TITLE
Some fixes

### PR DESCRIPTION
**Pull request by ghost**
Used normal object copy instead of deepCopy since TomlValueRef of kind Date, Time and DateTime don't contain any ref types inside.
For the removal of type checking in arrays - as per https://github.com/toml-lang/toml/blob/master/toml.md#user-content-array arrays can now be of mixed types. 

Also added handling for floats with exponents with leading zeroes

### CODE REVIEW

**Comment by ghost** [comment]
Another thing I might add - there are more-or-less updates tests in https://github.com/iarna/toml-spec-tests

**Comment by PMunch** [comment]
Hmm, mixed type arrays are not part of the 0.5.0 version of the spec, which is what this is currently up to date with. Could you split your fixes from this feature and submit this as two separate requests so that the 0.5.0 version can be correct according to the spec and we can start working on the 1.0.0 version of the spec separately.

And floats with exponents having leading zeroes is explicitly disallowed by the specification (both the v0.5.0 and the v1.0.0.):
In the float part: ["An exponent part is an E (upper or lower case) followed by an integer part (which follows the same rules as integer values)."](https://github.com/toml-lang/toml/tree/v0.5.0#float)
In the integer part: ["Leading zeros are not allowed."](https://github.com/toml-lang/toml/tree/v0.5.0#integer)
So this should continue to be a parsing error.

**Comment by PMunch** [comment]
Good thing there is a new test-suite. We really should make a proper one though, that covers 1.0.0 and commit to actually updating it..

**Comment by ghost** [comment]
@PMunch I updated the test suite in another branch in my fork, but not all tests pass :) They require more changes to parsing

**Comment by kaushalmodi** [comment]
@Yardanico If you rebase this PR to the current parsetoml master branch and force push to the same PR branch, it will resolve the travis error we are seeing right now. That issue got fixed in https://github.com/NimParsers/parsetoml/commit/376086763a5327478d44a0d61c774d2352668b0c .

**Comment by kaushalmodi** [comment]
@Yardanico @PMunch I have merged just the "Used normal object copy instead of deepCopy since TomlValueRef of kind Date, Time and DateTime don't contain any ref types inside." piece of this PR in https://github.com/NimParsers/parsetoml/pull/47 .

**Pull request closed without merging**
